# Generated by Django 2.1.7 on 2008-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posttags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
