# Generated by Django 2.1.7 on 2008-04-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20080422_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='Timestamp',
        ),
    ]
